#!/usr/bin/env bash

set -e

if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME is not set. Please set it to your Java installation path."
    exit 1
fi

rm -rf dist
mkdir dist

cd eclipse.jdt.ls/
JAVA_HOME=$JAVA_HOME ./mvnw clean verify -DskipTests

Lombok_JAR_URL="https://projectlombok.org/lombok-edge.jar"
curl -L -o lombok-edge.jar "$Lombok_JAR_URL"
mv lombok-edge.jar ./org.eclipse.jdt.ls.product/target/repository/plugins

cp -f ../script/jdtls.py ./org.eclipse.jdt.ls.product/target/repository/bin/jdtls.py

tar -czf ../dist/eclipse.jdt.ls.tar.gz -C ./org.eclipse.jdt.ls.product/target/repository .

mkdir -p ../dist/eclipse.jdt.ls
cp -r ./org.eclipse.jdt.ls.product/target/repository/* ../dist/eclipse.jdt.ls/

cd ../dist
zip -r eclipse.jdt.ls.zip eclipse.jdt.ls