name: CI

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    name: Build binary and upload to release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write 
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          maven: true

      - name: Prepare repo
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: 'recursive'

      - name: Build
        run: build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0      
        with:
          name: eclipse.jdt.ls.tar.gz
          path: dist/eclipse.jdt.ls.tar.gz

      - uses: softprops/action-gh-release@v1
        name: Upload binaries to release if release tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          draft: true
          files: dist/*
          overwrite: true
          body: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
